pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "https://github.com/chrkb1569/DevOps-Practice"
            }
        }

        stage('Build Project') {
            steps {
                sh './gradlew clean build'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t chrkb1569/jenkins:test .'
            }
        }

        stage('Push Docker Image') {
            steps {
                sh 'docker push chrkb1569/jenkins:test'
            }
        }
    }
}