pipeline {
    agent any

    tools {
        gradle 'gradle'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "https://github.com/chrkb1569/DevOps-Practice"
            }
        }

        stage('Build') {
            steps {
                dir("./CI-CD-Practice") {
                    sh "./gradlew clean build"
                }
            }
        }
    }
}